version: '3.7'
services:
  client:
    build: ./
    volumes:
      - ./:/app
      - /node_modules
    ports:
      - 8080:80
      - 5001:80
    container_name: client
    depends_on:
      - api
    links:
      - api
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - 3001:3001
    container_name: api