# build stage
FROM node:10 as build-stage

WORKDIR wiley
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
#FROM nginx:latest as production-stage
FROM ubuntu
RUN apt-get update && apt-get install -y \
    nginx
COPY nginx.default /etc/nginx/sites-available/default
COPY --from=build-stage wiley/dist /var/www/html
RUN chmod -R a+r /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
